---
#packer app provision
- name: Packer provision app
  hosts: all
  become: yes
  tasks:
    - name: Install ruby
      vars:
        packages:
          - ruby-full
          - ruby-bundler
          - build-essential
      apt:
        name: "{{ packages }}"
        update_cache: yes

